# Generated by Django 5.0.1 on 2024-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_placeorder_no_of_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeorder',
            name='no_of_item',
            field=models.IntegerField(default='true'),
        ),
    ]
