# Generated by Django 5.0.1 on 2024-02-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_placeorder_no_of_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='no_of_item',
            new_name='no_of_items',
        ),
    ]
